id: 43b8448763d44cb6953964a74c881676
initial_creation_type: ocr
source_metadata:
  volumes:
    122e924dc0544967ba2e0661d40be2c6:
      base_file: v011.txt
      image_group_id: I1PD95856
      title: དཔའ་བོ་གཅིག་པའི་སྒྲུབ་ཐབས།
      total_pages: 2107
      volume_number: 11
